/*
 * \file UDP_SCM\SAPL\SAPLsodapp.c
 *
 * *****************************************************************************
** Copyright (c) 2009,  Bernecker + Rainer Industrie-Elektronik Ges.m.b.H and
**                      IXXAT Automation GmbH
** All rights reserved, Bernecker + Rainer Industrie-Elektronik Ges.m.b.H
**
** This source code is free software; you can redistribute it and/or modify it
** under the terms of the BSD license (according to License.txt).
********************************************************************************
**
**   Workfile: SAPLsodapp.c
**    Summary: SAPLsodapp - Safety object dictionary managed by the application
**             SAPL, safety object dictionary for the safety application.
**             This file contains the SOD callback functions. Using these
**             SOD callback functions the application can manage its own
**             "application objects". An "application object" is an object that
**             is not located in the SOD (SAPLsod.c) and can be accessed via
**             these SOD callback function.
**
**     Author: M. Molnar
**
********************************************************************************
********************************************************************************
**
**  Functions: SAPL_SOD_DefaultValueSetClbk
**             SAPL_SOD_AttrGetClbk
**             SAPL_SOD_ReadClbk
**             SAPL_SOD_WriteClbk
**             SAPL_SOD_ActualLenSet
**             SAPL_SOD_ActualLenGet
**             SAPL_SOD_LockClbk
**             SAPL_SOD_UnlockClbk
**
**    Remarks:
**
*******************************************************************************/

/*******************************************************************************
**    compiler directives
*******************************************************************************/

/*******************************************************************************
**    include-files

*******************************************************************************/
#include "../include/UDP.h"

#if (SOD_cfg_APPLICATION_OBJ == EPLS_k_ENABLE)

  #include "SCFMapi.h"
  #include "SODapi.h"

/*******************************************************************************
**    global variables
*******************************************************************************/
  static BOOLEAN o_SodLocked; /* flag to store whether the application SOD
                                 locked or not */

  /*
  ** Variable definition for the Application object
  */
  /* Index 0x2100 Sub-index 0x01 */

  #define k_HDL_APP_OBJ_U8 (UINT32)1UL               /* Handle of the object */
  static UINT8 b_Def_appObjU8 SAFE_INIT_SEKTOR = 0U; /* Default value */
  static UINT8 b_Act_appObjU8 SAFE_NO_INIT_SEKTOR;   /* Actual value */
  static SOD_t_ATTR s_Attr_appObjU8 SAFE_INIT_SEKTOR =
    {
      SOD_k_ATTR_RO,       /* Attribute : Ready only */
      EPLS_k_UINT8,        /* Data type : Unsigned 8 */
      1U,                  /* Object length : 1 byte */
      &b_Def_appObjU8      /* Reference to the default value */
    };

  /* Index 0x2200 Sub-index 0x01 */
  #define k_MAX_LEN_APL_DOM_OBJ 100UL   /* maximum length of the
                                           application domain object */
  #define k_HDL_APP_OBJ_DOM (UINT32)2UL /* Handle of the object */
  /* Actual value of the application domain object */
  static UINT8 ab_Act_appObjDom[k_MAX_LEN_APL_DOM_OBJ] SAFE_NO_INIT_SEKTOR;
  /* Default value of the application domain object */
  static UINT8 ab_Def_appObjDom[k_MAX_LEN_APL_DOM_OBJ] SAFE_NO_INIT_SEKTOR;
  /* Actual length of the application domain object */
  static UINT32 dw_ActLenObjDom SAFE_NO_INIT_SEKTOR;
  static SOD_t_ATTR s_Attr_appObjDom SAFE_INIT_SEKTOR =
    {
      SOD_k_ATTR_RW,         /* Attribute : Ready only */
      EPLS_k_DOMAIN,         /* Data type : DOMAIN */
      k_MAX_LEN_APL_DOM_OBJ, /* Object length */
      ab_Def_appObjDom      /* Reference to the default value */
    };


/*******************************************************************************
**    Application specific Safety Object Dictionary callback functions
*******************************************************************************/
  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_DefaultValueSetClbk
  **
  ** Description : This function sets the default values for the application
  **               objects. The function must be provided by the application,
  **               if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** Parameters  : B_INSTNUM (IN)   - instance number
  **
  ** Returnvalue : TRUE             - success
  **               FALSE            - failure, error is generated by the SOD
  **                                  unit
  **
  *****************************************************************************/
  BOOLEAN SAPL_SOD_DefaultValueSetClbk(BYTE_B_INSTNUM)
  {
    UINT32 i; /* loop counter */

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* default value will be set */
    b_Act_appObjU8 = b_Def_appObjU8;

    for(i = 0UL; i < k_MAX_LEN_APL_DOM_OBJ; i++)
    {
      ab_Act_appObjDom[i] = (UINT8)i;
      ab_Def_appObjDom[i] = (UINT8)i;
    }
    /* Actual length of the application domain object is set */
    dw_ActLenObjDom = k_MAX_LEN_APL_DOM_OBJ;

    /* SOD lock flag is initialized */
    o_SodLocked = FALSE;


    SCFM_TACK_PATH();

    return TRUE;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_AttrGetClbk
  **
  ** Description : This function returns the attributes and the access handle
  **               of the via index/sub-index specified application object.
  **
  **               **Important:** This is the prototype of a callback function,
  **               which will be called by the SOD module if the index in the
  **               SOD is not available. The function must be provided by the
  **               application, if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** Parameters  : B_INSTNUM (IN)     - instance number
  **               w_idx (IN)         - index of object to be read
  **               b_subIdx (IN)      - sub-index of object to be read
  **               pdw_hdl (OUT)      - handle to specified SOD entry.
  **               pe_saplError (OUT) - error code for the application object
  **                                    access that has to be set by the
  **                                    application
  **
  ** Returnvalue : <> NULL           - pointer to the attributes of the SOD
  **                                   entry
  **               == NULL           - SOD entry not available or failure, error
  **                                   is generated by the SOD unit
  **
  *****************************************************************************/
  const SOD_t_ATTR *SAPL_SOD_AttrGetClbk(BYTE_B_INSTNUM_ UINT16 w_idx,
                                        UINT8 b_subIdx, PTR_TYPE *pdw_hdl,
                                        SOD_t_ABORT_CODES *pe_saplError)
  {
    SOD_t_ATTR *ps_attr = (SOD_t_ATTR *)NULL; /* pointer to the attributes */

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    switch (w_idx)
    {
      case 0x2100:
      {
        if (b_subIdx == 0x01U)
        {
          /* Handle of the object is set */
          *pdw_hdl = k_HDL_APP_OBJ_U8;
          /* Attribute pointer is set */
          ps_attr = &s_Attr_appObjU8;
        }
        else
        {

          /* Sub-index does not exist */
          *pe_saplError = SOD_ABT_SUB_IDX_DOES_NOT_EXIST;
        }
        break;
      }
      case 0x2200:
      {
        if (b_subIdx == 0x01U)
        {
          /* Handle of the object is set */
          *pdw_hdl = k_HDL_APP_OBJ_DOM;
          /* Attribute pointer is set */
          ps_attr = &s_Attr_appObjDom;
        }
        else
        {
          /* Sub-index does not exist */
          *pe_saplError = SOD_ABT_SUB_IDX_DOES_NOT_EXIST;
        }
        break;
      }
      default:
      {
        /* Object does not exist */
        *pe_saplError = SOD_ABT_OBJ_DOES_NOT_EXIST;
        break;
      }
    }

    SCFM_TACK_PATH();

    return ps_attr;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_ReadClbk
  **
  ** Description : This function is called for reading the objects
  **               managed by the application. It returns a pointer to the data
  **               (segment) of the application object. The segment position and
  **               size have to be specified via dw_offset and dw_size in case
  **               of segmented access.
  **
  **               **Important:** This is the prototype of a callback function,
  **               which will be called by the SOD module. The function must be
  **               provided by the application, if SOD_cfg_APPLICATION_OBJ are
  **               enabled.
  **
  ** Parameters  : B_INSTNUM (IN)     - instance number
  **               dw_hdl (IN)        - handle/reference to the SOD entry
  **               dw_offset (IN)     - start offset in bytes of the segment
  **                                    within the data block
  **               dw_size (IN)       - size in bytes of the segment
  **               pe_saplError (OUT) - error code for the application object
  **                                    access that has to be set by the
  **                                    application
  **
  ** Returnvalue : <> NULL            - pointer to the data segment in the SOD
  **               == NULL            - failure, error is generated by the SOD
  **                                    unit
  **
  *****************************************************************************/
  void *SAPL_SOD_ReadClbk(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl, UINT32 dw_offset,
                        UINT32 dw_size, SOD_t_ABORT_CODES *pe_saplError)
  {
    void *pv_objData = NULL; /* pointer to the data of the object */


    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* swith for the object handle */
    switch (dw_hdl)
    {
      case k_HDL_APP_OBJ_U8:
      {
        /* set pointer to the actual value */
        pv_objData = &b_Act_appObjU8;
        break;
      }
      case k_HDL_APP_OBJ_DOM:
      {
        /* if offset and size are valid */
        if ((dw_offset < k_MAX_LEN_APL_DOM_OBJ) &&
            (dw_size <= (k_MAX_LEN_APL_DOM_OBJ-dw_offset)))
        {
          /* set pointer to the actual value */
          pv_objData = &ab_Act_appObjDom[dw_offset];
        }
        else /* else offset and size are invalid */
        {
          *pe_saplError = SOD_ABT_LEN_IS_TOO_HIGH;
        }
        break;
      }
      default:
      {
        *pe_saplError = SOD_ABT_GENERAL_ERROR;
        break;
      }
    }

    SCFM_TACK_PATH();

    return pv_objData;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_WriteClbk
  **
  ** Description : This function is called for writing the objects managed by
  **               the application. It writes the specified data (segment) into
  **               the SOD. The segment position and size have to be specified
  **               via dw_offset and dw_size in case of segmented access.
  **
  **               **Important:** This is the prototype of a callback function,
  **               which will be called by the SOD module. The function must be
  **               provided by the application, if SOD_cfg_APPLICATION_OBJ are
  **               enabled.
  **
  ** Parameters  : B_INSTNUM (IN)   - instance number
  **               dw_hdl (IN)      - handle/reference to the SOD entry
  **               pv_data (IN)     - reference to the data to be written
  **               o_overwrite (IN) - if TRUE then a read only object can be
  **                                  overwritten by the application
  **               dw_offset (IN)   - start offset in bytes of the segment
  **                                  within the data block
  **               dw_size (IN)     - size in bytes of the segment
  **
  ** Returnvalue : Abort code       - See {SOD_t_ABORT_CODES}, error is
  **                                  generated by the SOD unit
  **
  *****************************************************************************/
  SOD_t_ABORT_CODES SAPL_SOD_WriteClbk(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl,
                                       const void *pv_data, BOOLEAN o_overwrite,
                                       UINT32 dw_offset, UINT32 dw_size)
  {
    SOD_t_ABORT_CODES e_ret = SOD_ABT_GENERAL_ERROR; /* return value */

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* size and offset are ignored (they are only relevant for the segmented
                                    transfer) */
    dw_size = dw_size;
    dw_offset = dw_offset;

    /* swith for the object handle */
    switch (dw_hdl)
    {
      case k_HDL_APP_OBJ_U8:
      {
        /* if overwrite flag is set */
        if (o_overwrite)
        {
          /* object is overwritten */
          b_Act_appObjU8 = *((UINT8 *)(pv_data));
          /* Write access was successful */
          e_ret = SOD_ABT_NO_ERROR;
        }
        else
        {
          /* object is not write able */
          e_ret = SOD_ABT_OBJ_NOT_WRITEABLE;
        }
        break;
      }
      case k_HDL_APP_OBJ_DOM:
      {
        /* if offset and size are valid */
        if ((dw_offset < k_MAX_LEN_APL_DOM_OBJ) &&
            (dw_size <= (k_MAX_LEN_APL_DOM_OBJ-dw_offset)))
        {
          /* data is written */
          MEMCOPY(&ab_Act_appObjDom[dw_offset], pv_data, dw_size); /*lint !e670
                          (Warning -- Possible access beyond array for function
                           'memcpy(void *, const void *, unsigned int)',
                           argument 3 (size=100) exceeds argument 2 (size=16))
                           dw_size is checked by the SSDOS */
          /* Write access was successful */
          e_ret = SOD_ABT_NO_ERROR;
        }
        else /* else offset and size are invalid */
        {
          e_ret = SOD_ABT_LEN_IS_TOO_HIGH;
        }
        break;
      }
      default:
      {
        /* return Error */
        break;
      }
    }

    SCFM_TACK_PATH();

    return e_ret;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_ActualLenSet
  **
  ** Description : This function sets the actual length of the given SOD object.
  **               Actual length is only available at EPLS_k_DOMAIN,
  **               EPLS_k_VISIBLE_STRING and EPLS_k_OCTET_STRING SOD objects,
  **               otherwise FATAL error must be generated.
  **
  **               **Important:** The function must be provided by the
  **               application, if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** See Also    : SAPL_SOD_ActualLenGet()
  **
  ** Parameters  : B_INSTNUM (IN) - instance number
  **               dw_hdl (IN)    - handle/reference to the SOD entry  got by
  **                                {SOD_AttrGetNext()} or {SOD_AttrGet()}
  **               dw_actLen (IN) - actual length to be set
  **
  ** Returnvalue : Abort code     - See {SOD_t_ABORT_CODES}, error is
  **                                generated by the SOD unit
  **
  *****************************************************************************/
  SOD_t_ABORT_CODES SAPL_SOD_ActualLenSet(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl,
                                          UINT32 dw_actLen)
  {
    SOD_t_ABORT_CODES e_ret = SOD_ABT_GENERAL_ERROR;
    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* swith for the object handle */
    switch (dw_hdl)
    {
      case k_HDL_APP_OBJ_DOM:
      {
        /* actual length is set */
        dw_ActLenObjDom = dw_actLen;

        e_ret = SOD_ABT_NO_ERROR;
        break;
      }
      default:
      {
        /* return Error */
        break;
      }
    }

    SCFM_TACK_PATH();

    return e_ret;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_ActualLenGet
  **
  ** Description : This function gets the actual length of the given SOD object.
  **               Actual length is only available at EPLS_k_DOMAIN,
  **               EPLS_k_VISIBLE_STRING and EPLS_k_OCTET_STRING SOD objects,
  **               otherwise the maximum length object is returned.
  **
  **               **Important:** The function must be provided by the
  **               application, if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** See Also    : SAPL_SOD_ActualLenSet()
  **
  ** Parameters  : B_INSTNUM (IN)   - instance number
  **               dw_hdl (IN)      - handle/reference to the SOD entry  got by
  **                                  {SOD_AttrGetNext()} or {SOD_AttrGet()}
  **               pdw_objLen (OUT) - reference to the object length,
  **                                  if the data type is EPLS_k_DOMAIN,
  **                                  EPLS_k_VISIBLE_STRING or
  **                                  EPLS_k_OCTET_STRING then actual length,
  **                                  otherwise maximum length.
  **
  ** Returnvalue : Abort code       - See {SOD_t_ABORT_CODES}, error is
  **                                  generated by the SOD unit
  **
  *****************************************************************************/
  SOD_t_ABORT_CODES SAPL_SOD_ActualLenGet(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl,
                                          UINT32 *pdw_objLen)
  {
    SOD_t_ABORT_CODES e_ret = SOD_ABT_GENERAL_ERROR; /* return value */

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* swith for the object handle */
    switch (dw_hdl)
    {
      case k_HDL_APP_OBJ_U8:
      {
        /* actual length is get */
        *pdw_objLen = s_Attr_appObjU8.dw_objLen;

        e_ret = SOD_ABT_NO_ERROR;
        break;
      }
      case k_HDL_APP_OBJ_DOM:
      {
        /* actual length is get */
        *pdw_objLen = dw_ActLenObjDom;

        e_ret = SOD_ABT_NO_ERROR;
        break;
      }
      default:
      {
        /* return Error */
        break;
      }
    }

    SCFM_TACK_PATH();

    return e_ret;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_LockClbk
  **
  ** Description : This function locks the access to the application objects.
  **
  **               **Important:** This function will be called from {SOD_Lock()}
  **               function. The function must be provided by the application,
  **               if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** See Also    : SAPL_SOD_UnlockClbk()
  **
  ** Parameters  : B_INSTNUM (IN)  - instance number
  **               dw_hdl (IN)     - handle/reference to the application object
  **                                 got by {SOD_AttrGetNext()} or
  **                                 {SOD_AttrGet()}
  **
  ** Returnvalue : TRUE            - locking succeeded
  **               FALSE           - locking failed, error is generated by the
  **                                 SOD unit
  **
  *****************************************************************************/
  BOOLEAN SAPL_SOD_LockClbk(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl)
  {
    BOOLEAN o_ret = FALSE; /* return value */

    /* To avoid warning. Locking and Unlocking mechanism are not used
                         in the demo */
    dw_hdl = dw_hdl;

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* if the application SOD has not been locked yet */
    if (!o_SodLocked)
    {
      o_SodLocked = TRUE;
      o_ret = TRUE;
    }
    /* no else : application SOD has been already locked */

    SCFM_TACK_PATH();

    return o_ret;
  }

  /*****************************************************************************
  **
  ** Function    : SAPL_SOD_UnlockClbk
  **
  ** Description : This function unlocks the access to the application objects.
  **
  **               **Important:** This function will be called from
  **               {SOD_Unlock()} function. The function must be provided by the
  **               application, if SOD_cfg_APPLICATION_OBJ are enabled.
  **
  ** See Also    : SAPL_SOD_LockClbk()
  **
  ** Parameters  : B_INSTNUM (IN)  - instance number
  **               dw_hdl (IN)     - handle/reference to the application object
  **                                 got by {SOD_AttrGetNext()} or
  **                                 {SOD_AttrGet()}
  **
  ** Returnvalue : TRUE            - unlocking succeeded
  **               FALSE           - unlocking failed, error is generated by the
  **                                 SOD unit
  **
  *****************************************************************************/
  BOOLEAN SAPL_SOD_UnlockClbk(BYTE_B_INSTNUM_ PTR_TYPE dw_hdl)
  {
    BOOLEAN o_ret = FALSE; /* return value */

    /* To avoid warning. Locking and Unlocking mechanism are not used
                         in the demo */
    dw_hdl = dw_hdl;

    #if (EPLS_cfg_MAX_INSTANCES > 1)
      b_instNum = b_instNum;
    #endif

    /* if the application SOD has been already locked */
    if (o_SodLocked)
    {
      o_SodLocked = FALSE;
      o_ret = TRUE;
    }
    /* no else : the application SOD has not been locked yet */

    SCFM_TACK_PATH();

    return o_ret;
  }
#endif

